### ISSUE TITLE
iOS and Android porting

### ISSUE THREAD

**Issue by Ninja-007** [jgaa/restc-cpp#17]
Thanks for providing this interesting library. I would like to use it for mobile plateforms.

Before starting I have some questions.
1. Asio comes in two flavours. 1. standalone without boost and second without boost. Is it possible to avoid boost completely and use standalone asio? 
2. Does it have IPv6 support? https://stackoverflow.com/questions/37637818/ipv6-app-store-rejection

Regards

**Comment by jgaa** [comment]
Hi,
1) The library use asio coroutines, which depends on boost coroutines and boost system. 
2) Ipv6 should work, but I have not tested it. That I have too do.

Regarding porting to mobile devices. 

Bost asio and the json serialization is template based, and currently the compilers produce quite large binaries. However, since the code already compiles with g++ and clang, it should work on Android and IOS, if the target device has sufficient resources. 

However, if I designed a REST library for embedded/IOT/Mobile devices, I would have avoided templates and may be even exceptions, in order to shrink the binary code.
