### ISSUE TITLE
Create a stable release if applicable

### ISSUE THREAD

**Issue by CodingSpiderFox** [jgaa/restc-cpp#9]
If possible at the current implementation status, I would like to have a stable release (not a pre release) available. 

I think it makes sense to have a stable release as I want to have this package available via the conan package manager.

But before I make a request to create a conan package from this library, it would help to have a stable version so the acceptance (by both the package creator and the users of the package) might be increased

**Comment by jgaa** [comment]
A stable release at this time is a bit of a catc22. I can't really say it's stable before I get solid feedback that it works well for a number of other developers. (That's basically what Beta is for). And most developers won't touch it before I have a stable release :)

There are no known bugs. All unit tests and functional tests pass on all supported platforms. I do plan to release a beta this week. (I planned the same the last week, but then some tests failed with Fedora, and it turned out to be a real bug that needed fixing.)

I can move the current branch to release, without adding any more features, when I know it's working well for beta testers, within a few weeks. But I depend on feedback. Else, I risk calling something stable that has serious flaws in it.

**Comment by CodingSpiderFox** [comment]
I understand and totally agree

**Comment by CodingSpiderFox** [comment]
Not relevant for me anymore
